// Code generated by gowinrt. DO NOT EDIT.

//go:build windows

//nolint:all
package streams

import (
	"syscall"
	"unsafe"

	"github.com/zandercodes/gowinrt/winrt"
)

const SignatureDataReader string = "rc(Windows.Storage.Streams.DataReader;{e2b50029-b4c1-4314-a4b8-fb813a2f275e})"

type DataReader struct {
	winrt.IUnknown
}

func (impl *DataReader) ReadBytes(valueSize uint32) ([]uint8, error) {
	itf := impl.MustQueryInterface(winrt.NewGUID(GUIDIDataReader))
	defer itf.Release()
	v := (*IDataReader)(unsafe.Pointer(itf))
	return v.ReadBytes(valueSize)
}

const GUIDiDataReaderStatics string = "11fcbfc8-f93a-471b-b121-f379e349313c"
const SignatureiDataReaderStatics string = "{11fcbfc8-f93a-471b-b121-f379e349313c}"

type iDataReaderStatics struct {
	winrt.IInspectable
}

type iDataReaderStaticsVtbl struct {
	winrt.IInspectableVtbl

	DataReaderFromBuffer uintptr
}

func (v *iDataReaderStatics) VTable() *iDataReaderStaticsVtbl {
	return (*iDataReaderStaticsVtbl)(unsafe.Pointer(v.RawVTable))
}

func DataReaderFromBuffer(buffer *IBuffer) (*DataReader, error) {
	inspectable, err := winrt.RoGetActivationFactory("Windows.Storage.Streams.DataReader", winrt.NewGUID(GUIDiDataReaderStatics))
	if err != nil {
		return nil, err
	}
	v := (*iDataReaderStatics)(unsafe.Pointer(inspectable))

	var out *DataReader
	hr, _, _ := syscall.SyscallN(
		v.VTable().DataReaderFromBuffer,
		uintptr(unsafe.Pointer(v)),      // this
		uintptr(unsafe.Pointer(buffer)), // in IBuffer
		uintptr(unsafe.Pointer(&out)),   // out DataReader
	)

	if hr != 0 {
		return nil, winrt.NewError(hr)
	}

	return out, nil
}
