// Code generated by gowinrt. DO NOT EDIT.

//go:build windows

//nolint:all
package streams

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
)

const GUIDIContentTypeProvider string = "97d098a5-3b99-4de9-88a5-e11d2f50c795"
const SignatureIContentTypeProvider string = "{97d098a5-3b99-4de9-88a5-e11d2f50c795}"

type IContentTypeProvider struct {
	ole.IInspectable
}

type IContentTypeProviderVtbl struct {
	ole.IInspectableVtbl

	GetContentType uintptr
}

func (v *IContentTypeProvider) VTable() *IContentTypeProviderVtbl {
	return (*IContentTypeProviderVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *IContentTypeProvider) GetContentType() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetContentType,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}
