// Code generated by gowinrt. DO NOT EDIT.

//go:build windows

//nolint:all
package streams

import (
	"syscall"
	"unsafe"

	"github.com/zandercodes/gowinrt/winrt"
)

const GUIDIRandomAccessStream string = "905a0fe1-bc53-11df-8c49-001e4fc686da"
const SignatureIRandomAccessStream string = "{905a0fe1-bc53-11df-8c49-001e4fc686da}"

type IRandomAccessStream struct {
	winrt.IInspectable
}

type IRandomAccessStreamVtbl struct {
	winrt.IInspectableVtbl

	GetSize           uintptr
	SetSize           uintptr
	GetInputStreamAt  uintptr
	GetOutputStreamAt uintptr
	GetPosition       uintptr
	Seek              uintptr
	CloneStream       uintptr
	GetCanRead        uintptr
	GetCanWrite       uintptr
}

func (v *IRandomAccessStream) VTable() *IRandomAccessStreamVtbl {
	return (*IRandomAccessStreamVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *IRandomAccessStream) GetSize() (uint64, error) {
	var out uint64
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetSize,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out uint64
	)

	if hr != 0 {
		return 0, winrt.NewError(hr)
	}

	return out, nil
}
