// Code generated by gowinrt. DO NOT EDIT.

//go:build windows

//nolint:all
package streams

import (
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/zandercodes/gowinrt/windows/foundation"
)

const GUIDIRandomAccessStreamWithContentType string = "cc254827-4b3d-438f-9232-10c76bc7e038"
const SignatureIRandomAccessStreamWithContentType string = "{cc254827-4b3d-438f-9232-10c76bc7e038}"

type IRandomAccessStreamWithContentType struct {
	ole.IInspectable
}

type IRandomAccessStreamWithContentTypeVtbl struct {
	ole.IInspectableVtbl
}

func (v *IRandomAccessStreamWithContentType) VTable() *IRandomAccessStreamWithContentTypeVtbl {
	return (*IRandomAccessStreamWithContentTypeVtbl)(unsafe.Pointer(v.RawVTable))
}

func (impl *IRandomAccessStreamWithContentType) GetSize() (uint64, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDIRandomAccessStream))
	defer itf.Release()
	v := (*IRandomAccessStream)(unsafe.Pointer(itf))
	return v.GetSize()
}

func (impl *IRandomAccessStreamWithContentType) ReadAsync(buffer *IBuffer, count uint32, options InputStreamOptions) (*foundation.IAsyncOperationWithProgress, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDIInputStream))
	defer itf.Release()
	v := (*IInputStream)(unsafe.Pointer(itf))
	return v.ReadAsync(buffer, count, options)
}
