// Code generated by gowinrt. DO NOT EDIT.

//go:build windows

//nolint:all
package streams

import (
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/zandercodes/gowinrt/windows/foundation"
)

const SignatureRandomAccessStreamReference string = "rc(Windows.Storage.Streams.RandomAccessStreamReference;{33ee3134-1dd6-4e3a-8067-d1c162e8642b})"

type RandomAccessStreamReference struct {
	ole.IUnknown
}

func (impl *RandomAccessStreamReference) OpenReadAsync() (*foundation.IAsyncOperation, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDIRandomAccessStreamReference))
	defer itf.Release()
	v := (*IRandomAccessStreamReference)(unsafe.Pointer(itf))
	return v.OpenReadAsync()
}
