// Code generated by gowinrt. DO NOT EDIT.

//go:build windows

//nolint:all
package advertisement

type BluetoothLEAdvertisementWatcherStatus int32

const SignatureBluetoothLEAdvertisementWatcherStatus string = "enum(Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementWatcherStatus;i4)"

const (
	BluetoothLEAdvertisementWatcherStatusCreated  BluetoothLEAdvertisementWatcherStatus = 0
	BluetoothLEAdvertisementWatcherStatusStarted  BluetoothLEAdvertisementWatcherStatus = 1
	BluetoothLEAdvertisementWatcherStatusStopping BluetoothLEAdvertisementWatcherStatus = 2
	BluetoothLEAdvertisementWatcherStatusStopped  BluetoothLEAdvertisementWatcherStatus = 3
	BluetoothLEAdvertisementWatcherStatusAborted  BluetoothLEAdvertisementWatcherStatus = 4
)
