// Code generated by gowinrt. DO NOT EDIT.

//go:build windows

//nolint:all
package advertisement

import (
	"syscall"
	"unsafe"

	"github.com/zandercodes/gowinrt/windows/devices/bluetooth"
	"github.com/zandercodes/gowinrt/winrt"
)

const SignatureBluetoothLEAdvertisementWatcherStoppedEventArgs string = "rc(Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementWatcherStoppedEventArgs;{dd40f84d-e7b9-43e3-9c04-0685d085fd8c})"

type BluetoothLEAdvertisementWatcherStoppedEventArgs struct {
	winrt.IUnknown
}

func (impl *BluetoothLEAdvertisementWatcherStoppedEventArgs) GetError() (bluetooth.BluetoothError, error) {
	itf := impl.MustQueryInterface(winrt.NewGUID(GUIDiBluetoothLEAdvertisementWatcherStoppedEventArgs))
	defer itf.Release()
	v := (*iBluetoothLEAdvertisementWatcherStoppedEventArgs)(unsafe.Pointer(itf))
	return v.GetError()
}

const GUIDiBluetoothLEAdvertisementWatcherStoppedEventArgs string = "dd40f84d-e7b9-43e3-9c04-0685d085fd8c"
const SignatureiBluetoothLEAdvertisementWatcherStoppedEventArgs string = "{dd40f84d-e7b9-43e3-9c04-0685d085fd8c}"

type iBluetoothLEAdvertisementWatcherStoppedEventArgs struct {
	winrt.IInspectable
}

type iBluetoothLEAdvertisementWatcherStoppedEventArgsVtbl struct {
	winrt.IInspectableVtbl

	GetError uintptr
}

func (v *iBluetoothLEAdvertisementWatcherStoppedEventArgs) VTable() *iBluetoothLEAdvertisementWatcherStoppedEventArgsVtbl {
	return (*iBluetoothLEAdvertisementWatcherStoppedEventArgsVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iBluetoothLEAdvertisementWatcherStoppedEventArgs) GetError() (bluetooth.BluetoothError, error) {
	var out bluetooth.BluetoothError
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetError,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out bluetooth.BluetoothError
	)

	if hr != 0 {
		return bluetooth.BluetoothErrorSuccess, winrt.NewError(hr)
	}

	return out, nil
}
