// Code generated by gowinrt. DO NOT EDIT.

//go:build windows

//nolint:all
package bluetooth

type BluetoothConnectionStatus int32

const SignatureBluetoothConnectionStatus string = "enum(Windows.Devices.Bluetooth.BluetoothConnectionStatus;i4)"

const (
	BluetoothConnectionStatusDisconnected BluetoothConnectionStatus = 0
	BluetoothConnectionStatusConnected    BluetoothConnectionStatus = 1
)
