// Code generated by gowinrt. DO NOT EDIT.

//go:build windows

//nolint:all
package bluetooth

import (
	"syscall"
	"unsafe"

	"github.com/zandercodes/gowinrt/winrt"
)

const SignatureBluetoothDeviceId string = "rc(Windows.Devices.Bluetooth.BluetoothDeviceId;{c17949af-57c1-4642-bcce-e6c06b20ae76})"

type BluetoothDeviceId struct {
	winrt.IUnknown
}

func (impl *BluetoothDeviceId) GetId() (string, error) {
	itf := impl.MustQueryInterface(winrt.NewGUID(GUIDiBluetoothDeviceId))
	defer itf.Release()
	v := (*iBluetoothDeviceId)(unsafe.Pointer(itf))
	return v.GetId()
}

func (impl *BluetoothDeviceId) GetIsClassicDevice() (bool, error) {
	itf := impl.MustQueryInterface(winrt.NewGUID(GUIDiBluetoothDeviceId))
	defer itf.Release()
	v := (*iBluetoothDeviceId)(unsafe.Pointer(itf))
	return v.GetIsClassicDevice()
}

func (impl *BluetoothDeviceId) GetIsLowEnergyDevice() (bool, error) {
	itf := impl.MustQueryInterface(winrt.NewGUID(GUIDiBluetoothDeviceId))
	defer itf.Release()
	v := (*iBluetoothDeviceId)(unsafe.Pointer(itf))
	return v.GetIsLowEnergyDevice()
}

const GUIDiBluetoothDeviceId string = "c17949af-57c1-4642-bcce-e6c06b20ae76"
const SignatureiBluetoothDeviceId string = "{c17949af-57c1-4642-bcce-e6c06b20ae76}"

type iBluetoothDeviceId struct {
	winrt.IInspectable
}

type iBluetoothDeviceIdVtbl struct {
	winrt.IInspectableVtbl

	GetId                uintptr
	GetIsClassicDevice   uintptr
	GetIsLowEnergyDevice uintptr
}

func (v *iBluetoothDeviceId) VTable() *iBluetoothDeviceIdVtbl {
	return (*iBluetoothDeviceIdVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iBluetoothDeviceId) GetId() (string, error) {
	var outHStr winrt.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetId,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", winrt.NewError(hr)
	}

	out := outHStr.String()
	winrt.DeleteHString(outHStr)
	return out, nil
}

func (v *iBluetoothDeviceId) GetIsClassicDevice() (bool, error) {
	var out bool
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetIsClassicDevice,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out bool
	)

	if hr != 0 {
		return false, winrt.NewError(hr)
	}

	return out, nil
}

func (v *iBluetoothDeviceId) GetIsLowEnergyDevice() (bool, error) {
	var out bool
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetIsLowEnergyDevice,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out bool
	)

	if hr != 0 {
		return false, winrt.NewError(hr)
	}

	return out, nil
}
