// Code generated by gowinrt. DO NOT EDIT.

//go:build windows

//nolint:all
package genericattributeprofile

import (
	"syscall"
	"unsafe"

	"github.com/zandercodes/gowinrt/windows/foundation/collections"
	"github.com/zandercodes/gowinrt/winrt"
)

const SignatureGattDeviceServicesResult string = "rc(Windows.Devices.Bluetooth.GenericAttributeProfile.GattDeviceServicesResult;{171dd3ee-016d-419d-838a-576cf475a3d8})"

type GattDeviceServicesResult struct {
	winrt.IUnknown
}

func (impl *GattDeviceServicesResult) GetStatus() (GattCommunicationStatus, error) {
	itf := impl.MustQueryInterface(winrt.NewGUID(GUIDiGattDeviceServicesResult))
	defer itf.Release()
	v := (*iGattDeviceServicesResult)(unsafe.Pointer(itf))
	return v.GetStatus()
}

func (impl *GattDeviceServicesResult) GetServices() (*collections.IVectorView, error) {
	itf := impl.MustQueryInterface(winrt.NewGUID(GUIDiGattDeviceServicesResult))
	defer itf.Release()
	v := (*iGattDeviceServicesResult)(unsafe.Pointer(itf))
	return v.GetServices()
}

const GUIDiGattDeviceServicesResult string = "171dd3ee-016d-419d-838a-576cf475a3d8"
const SignatureiGattDeviceServicesResult string = "{171dd3ee-016d-419d-838a-576cf475a3d8}"

type iGattDeviceServicesResult struct {
	winrt.IInspectable
}

type iGattDeviceServicesResultVtbl struct {
	winrt.IInspectableVtbl

	GetStatus        uintptr
	GetProtocolError uintptr
	GetServices      uintptr
}

func (v *iGattDeviceServicesResult) VTable() *iGattDeviceServicesResultVtbl {
	return (*iGattDeviceServicesResultVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iGattDeviceServicesResult) GetStatus() (GattCommunicationStatus, error) {
	var out GattCommunicationStatus
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetStatus,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out GattCommunicationStatus
	)

	if hr != 0 {
		return GattCommunicationStatusSuccess, winrt.NewError(hr)
	}

	return out, nil
}

func (v *iGattDeviceServicesResult) GetServices() (*collections.IVectorView, error) {
	var out *collections.IVectorView
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetServices,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out collections.IVectorView
	)

	if hr != 0 {
		return nil, winrt.NewError(hr)
	}

	return out, nil
}
