// Code generated by gowinrt. DO NOT EDIT.

//go:build windows

//nolint:all
package genericattributeprofile

import (
	"syscall"
	"unsafe"

	"github.com/zandercodes/gowinrt/windows/storage/streams"
	"github.com/zandercodes/gowinrt/winrt"
)

const SignatureGattReadResult string = "rc(Windows.Devices.Bluetooth.GenericAttributeProfile.GattReadResult;{63a66f08-1aea-4c4c-a50f-97bae474b348})"

type GattReadResult struct {
	winrt.IUnknown
}

func (impl *GattReadResult) GetStatus() (GattCommunicationStatus, error) {
	itf := impl.MustQueryInterface(winrt.NewGUID(GUIDiGattReadResult))
	defer itf.Release()
	v := (*iGattReadResult)(unsafe.Pointer(itf))
	return v.GetStatus()
}

func (impl *GattReadResult) GetValue() (*streams.IBuffer, error) {
	itf := impl.MustQueryInterface(winrt.NewGUID(GUIDiGattReadResult))
	defer itf.Release()
	v := (*iGattReadResult)(unsafe.Pointer(itf))
	return v.GetValue()
}

const GUIDiGattReadResult string = "63a66f08-1aea-4c4c-a50f-97bae474b348"
const SignatureiGattReadResult string = "{63a66f08-1aea-4c4c-a50f-97bae474b348}"

type iGattReadResult struct {
	winrt.IInspectable
}

type iGattReadResultVtbl struct {
	winrt.IInspectableVtbl

	GetStatus uintptr
	GetValue  uintptr
}

func (v *iGattReadResult) VTable() *iGattReadResultVtbl {
	return (*iGattReadResultVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iGattReadResult) GetStatus() (GattCommunicationStatus, error) {
	var out GattCommunicationStatus
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetStatus,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out GattCommunicationStatus
	)

	if hr != 0 {
		return GattCommunicationStatusSuccess, winrt.NewError(hr)
	}

	return out, nil
}

func (v *iGattReadResult) GetValue() (*streams.IBuffer, error) {
	var out *streams.IBuffer
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetValue,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out streams.IBuffer
	)

	if hr != 0 {
		return nil, winrt.NewError(hr)
	}

	return out, nil
}

const GUIDiGattReadResult2 string = "a10f50a0-fb43-48af-baaa-638a5c6329fe"
const SignatureiGattReadResult2 string = "{a10f50a0-fb43-48af-baaa-638a5c6329fe}"

type iGattReadResult2 struct {
	winrt.IInspectable
}

type iGattReadResult2Vtbl struct {
	winrt.IInspectableVtbl

	GetProtocolError uintptr
}

func (v *iGattReadResult2) VTable() *iGattReadResult2Vtbl {
	return (*iGattReadResult2Vtbl)(unsafe.Pointer(v.RawVTable))
}
