// Code generated by gowinrt. DO NOT EDIT.

//go:build windows

//nolint:all
package foundation

import (
	"sync"
	"time"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/zandercodes/gowinrt/internal/delegate"
	"github.com/zandercodes/gowinrt/internal/kernel32"
)

const GUIDAsyncOperationProgressHandler string = "55690902-0aab-421a-8778-f8ce5026d758"
const SignatureAsyncOperationProgressHandler string = "delegate({55690902-0aab-421a-8778-f8ce5026d758})"

type AsyncOperationProgressHandler struct {
	ole.IUnknown
	sync.Mutex
	refs uintptr
	IID  ole.GUID
}

type AsyncOperationProgressHandlerVtbl struct {
	ole.IUnknownVtbl
	Invoke uintptr
}

type AsyncOperationProgressHandlerCallback func(instance *AsyncOperationProgressHandler, asyncInfo *IAsyncOperationWithProgress, progressInfo unsafe.Pointer)

var callbacksAsyncOperationProgressHandler = &asyncOperationProgressHandlerCallbacks{
	mu:        &sync.Mutex{},
	callbacks: make(map[unsafe.Pointer]AsyncOperationProgressHandlerCallback),
}

var releaseChannelsAsyncOperationProgressHandler = &asyncOperationProgressHandlerReleaseChannels{
	mu:    &sync.Mutex{},
	chans: make(map[unsafe.Pointer]chan struct{}),
}

func NewAsyncOperationProgressHandler(iid *ole.GUID, callback AsyncOperationProgressHandlerCallback) *AsyncOperationProgressHandler {
	size := unsafe.Sizeof(*(*AsyncOperationProgressHandler)(nil))
	instPtr := kernel32.Malloc(size)
	inst := (*AsyncOperationProgressHandler)(instPtr)

	callbacks := delegate.Register(instPtr, inst)

	sizeVTable := unsafe.Sizeof(*(*AsyncOperationProgressHandlerVtbl)(nil))
	vTablePtr := kernel32.Malloc(sizeVTable)

	inst.RawVTable = (*interface{})(vTablePtr)

	vTable := (*AsyncOperationProgressHandlerVtbl)(vTablePtr)
	vTable.IUnknownVtbl = ole.IUnknownVtbl{
		QueryInterface: callbacks.QueryInterface,
		AddRef:         callbacks.AddRef,
		Release:        callbacks.Release,
	}
	vTable.Invoke = callbacks.Invoke

	inst.IID = *iid
	inst.Mutex = sync.Mutex{}
	inst.refs = 0

	callbacksAsyncOperationProgressHandler.add(unsafe.Pointer(inst), callback)
	releaseChannelsAsyncOperationProgressHandler.acquire(unsafe.Pointer(inst))

	inst.addRef()
	return inst
}

func (r *AsyncOperationProgressHandler) GetIID() *ole.GUID {
	return &r.IID
}

func (r *AsyncOperationProgressHandler) addRef() uintptr {
	r.Lock()
	defer r.Unlock()
	r.refs++
	return r.refs
}

func (r *AsyncOperationProgressHandler) removeRef() uintptr {
	r.Lock()
	defer r.Unlock()
	if r.refs > 0 {
		r.refs--
	}
	return r.refs
}

func (instance *AsyncOperationProgressHandler) Invoke(instancePtr, rawArgs0, rawArgs1, rawArgs2, rawArgs3, rawArgs4, rawArgs5, rawArgs6, rawArgs7, rawArgs8 unsafe.Pointer) uintptr {
	asyncInfoPtr := rawArgs0
	progressInfoPtr := rawArgs1

	asyncInfo := (*IAsyncOperationWithProgress)(asyncInfoPtr)
	progressInfo := (unsafe.Pointer)(progressInfoPtr)
	if callback, ok := callbacksAsyncOperationProgressHandler.get(instancePtr); ok {
		callback(instance, asyncInfo, progressInfo)
	}
	return ole.S_OK
}

func (instance *AsyncOperationProgressHandler) AddRef() uintptr {
	return instance.addRef()
}

func (instance *AsyncOperationProgressHandler) Release() uintptr {
	rem := instance.removeRef()
	if rem == 0 {
		instancePtr := unsafe.Pointer(instance)
		callbacksAsyncOperationProgressHandler.delete(instancePtr)
		releaseChannelsAsyncOperationProgressHandler.release(instancePtr)
		kernel32.Free(unsafe.Pointer(instance.RawVTable))
		kernel32.Free(instancePtr)
	}
	return rem
}

type asyncOperationProgressHandlerCallbacks struct {
	mu        *sync.Mutex
	callbacks map[unsafe.Pointer]AsyncOperationProgressHandlerCallback
}

func (m *asyncOperationProgressHandlerCallbacks) add(p unsafe.Pointer, v AsyncOperationProgressHandlerCallback) {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.callbacks[p] = v
}

func (m *asyncOperationProgressHandlerCallbacks) get(p unsafe.Pointer) (AsyncOperationProgressHandlerCallback, bool) {
	m.mu.Lock()
	defer m.mu.Unlock()
	v, ok := m.callbacks[p]
	return v, ok
}

func (m *asyncOperationProgressHandlerCallbacks) delete(p unsafe.Pointer) {
	m.mu.Lock()
	defer m.mu.Unlock()
	delete(m.callbacks, p)
}

type asyncOperationProgressHandlerReleaseChannels struct {
	mu    *sync.Mutex
	chans map[unsafe.Pointer]chan struct{}
}

func (m *asyncOperationProgressHandlerReleaseChannels) acquire(p unsafe.Pointer) {
	m.mu.Lock()
	defer m.mu.Unlock()

	c := make(chan struct{})
	m.chans[p] = c

	go func() {
		t := time.NewTimer(time.Minute)
		for {
			select {
			case <-t.C:
				t.Reset(time.Minute)
			case <-c:
				t.Stop()
				return
			}
		}
	}()
}

func (m *asyncOperationProgressHandlerReleaseChannels) release(p unsafe.Pointer) {
	m.mu.Lock()
	defer m.mu.Unlock()

	if c, ok := m.chans[p]; ok {
		close(c)
		delete(m.chans, p)
	}
}
