// Code generated by gowinrt. DO NOT EDIT.

//go:build windows

//nolint:all
package foundation

import (
	"sync"
	"time"
	"unsafe"

	"github.com/zandercodes/gowinrt/internal/delegate"
	"github.com/zandercodes/gowinrt/internal/kernel32"
	"github.com/zandercodes/gowinrt/winrt"
)

const GUIDAsyncOperationWithProgressCompletedHandler string = "e85df41d-6aa7-46e3-a8e2-f009d840c627"
const SignatureAsyncOperationWithProgressCompletedHandler string = "delegate({e85df41d-6aa7-46e3-a8e2-f009d840c627})"

type AsyncOperationWithProgressCompletedHandler struct {
	winrt.IUnknown
	sync.Mutex
	refs uintptr
	IID  winrt.GUID
}

type AsyncOperationWithProgressCompletedHandlerVtbl struct {
	winrt.IUnknownVtbl
	Invoke uintptr
}

type AsyncOperationWithProgressCompletedHandlerCallback func(instance *AsyncOperationWithProgressCompletedHandler, asyncInfo *IAsyncOperationWithProgress, asyncStatus AsyncStatus)

var callbacksAsyncOperationWithProgressCompletedHandler = &asyncOperationWithProgressCompletedHandlerCallbacks{
	mu:        &sync.Mutex{},
	callbacks: make(map[unsafe.Pointer]AsyncOperationWithProgressCompletedHandlerCallback),
}

var releaseChannelsAsyncOperationWithProgressCompletedHandler = &asyncOperationWithProgressCompletedHandlerReleaseChannels{
	mu:    &sync.Mutex{},
	chans: make(map[unsafe.Pointer]chan struct{}),
}

func NewAsyncOperationWithProgressCompletedHandler(iid *winrt.GUID, callback AsyncOperationWithProgressCompletedHandlerCallback) *AsyncOperationWithProgressCompletedHandler {
	size := unsafe.Sizeof(*(*AsyncOperationWithProgressCompletedHandler)(nil))
	instPtr := kernel32.Malloc(size)
	inst := (*AsyncOperationWithProgressCompletedHandler)(instPtr)

	callbacks := delegate.Register(instPtr, inst)

	sizeVTable := unsafe.Sizeof(*(*AsyncOperationWithProgressCompletedHandlerVtbl)(nil))
	vTablePtr := kernel32.Malloc(sizeVTable)

	inst.RawVTable = (*interface{})(vTablePtr)

	vTable := (*AsyncOperationWithProgressCompletedHandlerVtbl)(vTablePtr)
	vTable.IUnknownVtbl = winrt.IUnknownVtbl{
		QueryInterface: callbacks.QueryInterface,
		AddRef:         callbacks.AddRef,
		Release:        callbacks.Release,
	}
	vTable.Invoke = callbacks.Invoke

	inst.IID = *iid
	inst.Mutex = sync.Mutex{}
	inst.refs = 0

	callbacksAsyncOperationWithProgressCompletedHandler.add(unsafe.Pointer(inst), callback)
	releaseChannelsAsyncOperationWithProgressCompletedHandler.acquire(unsafe.Pointer(inst))

	inst.addRef()
	return inst
}

func (r *AsyncOperationWithProgressCompletedHandler) GetIID() *winrt.GUID {
	return &r.IID
}

func (r *AsyncOperationWithProgressCompletedHandler) addRef() uintptr {
	r.Lock()
	defer r.Unlock()
	r.refs++
	return r.refs
}

func (r *AsyncOperationWithProgressCompletedHandler) removeRef() uintptr {
	r.Lock()
	defer r.Unlock()
	if r.refs > 0 {
		r.refs--
	}
	return r.refs
}

func (instance *AsyncOperationWithProgressCompletedHandler) Invoke(instancePtr, rawArgs0, rawArgs1, rawArgs2, rawArgs3, rawArgs4, rawArgs5, rawArgs6, rawArgs7, rawArgs8 unsafe.Pointer) uintptr {
	asyncInfoPtr := rawArgs0
	asyncStatusRaw := (int32)(uintptr(rawArgs1))

	asyncInfo := (*IAsyncOperationWithProgress)(asyncInfoPtr)
	asyncStatus := (AsyncStatus)(asyncStatusRaw)
	if callback, ok := callbacksAsyncOperationWithProgressCompletedHandler.get(instancePtr); ok {
		callback(instance, asyncInfo, asyncStatus)
	}
	return winrt.S_OK
}

func (instance *AsyncOperationWithProgressCompletedHandler) AddRef() uintptr {
	return instance.addRef()
}

func (instance *AsyncOperationWithProgressCompletedHandler) Release() uintptr {
	rem := instance.removeRef()
	if rem == 0 {
		instancePtr := unsafe.Pointer(instance)
		callbacksAsyncOperationWithProgressCompletedHandler.delete(instancePtr)
		releaseChannelsAsyncOperationWithProgressCompletedHandler.release(instancePtr)
		kernel32.Free(unsafe.Pointer(instance.RawVTable))
		kernel32.Free(instancePtr)
	}
	return rem
}

type asyncOperationWithProgressCompletedHandlerCallbacks struct {
	mu        *sync.Mutex
	callbacks map[unsafe.Pointer]AsyncOperationWithProgressCompletedHandlerCallback
}

func (m *asyncOperationWithProgressCompletedHandlerCallbacks) add(p unsafe.Pointer, v AsyncOperationWithProgressCompletedHandlerCallback) {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.callbacks[p] = v
}

func (m *asyncOperationWithProgressCompletedHandlerCallbacks) get(p unsafe.Pointer) (AsyncOperationWithProgressCompletedHandlerCallback, bool) {
	m.mu.Lock()
	defer m.mu.Unlock()
	v, ok := m.callbacks[p]
	return v, ok
}

func (m *asyncOperationWithProgressCompletedHandlerCallbacks) delete(p unsafe.Pointer) {
	m.mu.Lock()
	defer m.mu.Unlock()
	delete(m.callbacks, p)
}

type asyncOperationWithProgressCompletedHandlerReleaseChannels struct {
	mu    *sync.Mutex
	chans map[unsafe.Pointer]chan struct{}
}

func (m *asyncOperationWithProgressCompletedHandlerReleaseChannels) acquire(p unsafe.Pointer) {
	m.mu.Lock()
	defer m.mu.Unlock()

	c := make(chan struct{})
	m.chans[p] = c

	go func() {
		t := time.NewTimer(time.Minute)
		for {
			select {
			case <-t.C:
				t.Reset(time.Minute)
			case <-c:
				t.Stop()
				return
			}
		}
	}()
}

func (m *asyncOperationWithProgressCompletedHandlerReleaseChannels) release(p unsafe.Pointer) {
	m.mu.Lock()
	defer m.mu.Unlock()

	if c, ok := m.chans[p]; ok {
		close(c)
		delete(m.chans, p)
	}
}
