// Code generated by gowinrt. DO NOT EDIT.

//go:build windows

//nolint:all
package foundation

const SignatureDateTime string = "struct(Windows.Foundation.DateTime;i8)"

type DateTime struct {
	UniversalTime int64
}
