// Code generated by gowinrt. DO NOT EDIT.

//go:build windows

//nolint:all
package foundation

import (
	"sync"
	"time"
	"unsafe"

	"github.com/zandercodes/gowinrt/internal/delegate"
	"github.com/zandercodes/gowinrt/internal/kernel32"
	"github.com/zandercodes/gowinrt/winrt"
)

const GUIDDeferralCompletedHandler string = "ed32a372-f3c8-4faa-9cfb-470148da3888"
const SignatureDeferralCompletedHandler string = "delegate({ed32a372-f3c8-4faa-9cfb-470148da3888})"

type DeferralCompletedHandler struct {
	winrt.IUnknown
	sync.Mutex
	refs uintptr
	IID  winrt.GUID
}

type DeferralCompletedHandlerVtbl struct {
	winrt.IUnknownVtbl
	Invoke uintptr
}

type DeferralCompletedHandlerCallback func(instance *DeferralCompletedHandler)

var callbacksDeferralCompletedHandler = &deferralCompletedHandlerCallbacks{
	mu:        &sync.Mutex{},
	callbacks: make(map[unsafe.Pointer]DeferralCompletedHandlerCallback),
}

var releaseChannelsDeferralCompletedHandler = &deferralCompletedHandlerReleaseChannels{
	mu:    &sync.Mutex{},
	chans: make(map[unsafe.Pointer]chan struct{}),
}

func NewDeferralCompletedHandler(iid *winrt.GUID, callback DeferralCompletedHandlerCallback) *DeferralCompletedHandler {
	size := unsafe.Sizeof(*(*DeferralCompletedHandler)(nil))
	instPtr := kernel32.Malloc(size)
	inst := (*DeferralCompletedHandler)(instPtr)

	callbacks := delegate.Register(instPtr, inst)

	sizeVTable := unsafe.Sizeof(*(*DeferralCompletedHandlerVtbl)(nil))
	vTablePtr := kernel32.Malloc(sizeVTable)

	inst.RawVTable = (*interface{})(vTablePtr)

	vTable := (*DeferralCompletedHandlerVtbl)(vTablePtr)
	vTable.IUnknownVtbl = winrt.IUnknownVtbl{
		QueryInterface: callbacks.QueryInterface,
		AddRef:         callbacks.AddRef,
		Release:        callbacks.Release,
	}
	vTable.Invoke = callbacks.Invoke

	inst.IID = *iid
	inst.Mutex = sync.Mutex{}
	inst.refs = 0

	callbacksDeferralCompletedHandler.add(unsafe.Pointer(inst), callback)
	releaseChannelsDeferralCompletedHandler.acquire(unsafe.Pointer(inst))

	inst.addRef()
	return inst
}

func (r *DeferralCompletedHandler) GetIID() *winrt.GUID {
	return &r.IID
}

func (r *DeferralCompletedHandler) addRef() uintptr {
	r.Lock()
	defer r.Unlock()
	r.refs++
	return r.refs
}

func (r *DeferralCompletedHandler) removeRef() uintptr {
	r.Lock()
	defer r.Unlock()
	if r.refs > 0 {
		r.refs--
	}
	return r.refs
}

func (instance *DeferralCompletedHandler) Invoke(instancePtr, rawArgs0, rawArgs1, rawArgs2, rawArgs3, rawArgs4, rawArgs5, rawArgs6, rawArgs7, rawArgs8 unsafe.Pointer) uintptr {

	if callback, ok := callbacksDeferralCompletedHandler.get(instancePtr); ok {
		callback(instance)
	}
	return winrt.S_OK
}

func (instance *DeferralCompletedHandler) AddRef() uintptr {
	return instance.addRef()
}

func (instance *DeferralCompletedHandler) Release() uintptr {
	rem := instance.removeRef()
	if rem == 0 {
		instancePtr := unsafe.Pointer(instance)
		callbacksDeferralCompletedHandler.delete(instancePtr)
		releaseChannelsDeferralCompletedHandler.release(instancePtr)
		kernel32.Free(unsafe.Pointer(instance.RawVTable))
		kernel32.Free(instancePtr)
	}
	return rem
}

type deferralCompletedHandlerCallbacks struct {
	mu        *sync.Mutex
	callbacks map[unsafe.Pointer]DeferralCompletedHandlerCallback
}

func (m *deferralCompletedHandlerCallbacks) add(p unsafe.Pointer, v DeferralCompletedHandlerCallback) {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.callbacks[p] = v
}

func (m *deferralCompletedHandlerCallbacks) get(p unsafe.Pointer) (DeferralCompletedHandlerCallback, bool) {
	m.mu.Lock()
	defer m.mu.Unlock()
	v, ok := m.callbacks[p]
	return v, ok
}

func (m *deferralCompletedHandlerCallbacks) delete(p unsafe.Pointer) {
	m.mu.Lock()
	defer m.mu.Unlock()
	delete(m.callbacks, p)
}

type deferralCompletedHandlerReleaseChannels struct {
	mu    *sync.Mutex
	chans map[unsafe.Pointer]chan struct{}
}

func (m *deferralCompletedHandlerReleaseChannels) acquire(p unsafe.Pointer) {
	m.mu.Lock()
	defer m.mu.Unlock()

	c := make(chan struct{})
	m.chans[p] = c

	go func() {
		t := time.NewTimer(time.Minute)
		for {
			select {
			case <-t.C:
				t.Reset(time.Minute)
			case <-c:
				t.Stop()
				return
			}
		}
	}()
}

func (m *deferralCompletedHandlerReleaseChannels) release(p unsafe.Pointer) {
	m.mu.Lock()
	defer m.mu.Unlock()

	if c, ok := m.chans[p]; ok {
		close(c)
		delete(m.chans, p)
	}
}
