// Code generated by gowinrt. DO NOT EDIT.

//go:build windows

//nolint:all
package foundation

const SignatureEventRegistrationToken string = "struct(Windows.Foundation.EventRegistrationToken;i8)"

type EventRegistrationToken struct {
	Value int64
}
