// Code generated by gowinrt. DO NOT EDIT.

//go:build windows

//nolint:all
package foundation

const SignatureHResult string = "struct(Windows.Foundation.HResult;i4)"

type HResult struct {
	Value int32
}
