// Code generated by gowinrt. DO NOT EDIT.

//go:build windows

//nolint:all
package foundation

import (
	"syscall"
	"unsafe"

	"github.com/zandercodes/gowinrt/winrt"
)

const GUIDIAsyncInfo string = "00000036-0000-0000-c000-000000000046"
const SignatureIAsyncInfo string = "{00000036-0000-0000-c000-000000000046}"

type IAsyncInfo struct {
	winrt.IInspectable
}

type IAsyncInfoVtbl struct {
	winrt.IInspectableVtbl

	GetId        uintptr
	GetStatus    uintptr
	GetErrorCode uintptr
	Cancel       uintptr
	Close        uintptr
}

func (v *IAsyncInfo) VTable() *IAsyncInfoVtbl {
	return (*IAsyncInfoVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *IAsyncInfo) GetId() (uint32, error) {
	var out uint32
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetId,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out uint32
	)

	if hr != 0 {
		return 0, winrt.NewError(hr)
	}

	return out, nil
}

func (v *IAsyncInfo) GetStatus() (AsyncStatus, error) {
	var out AsyncStatus
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetStatus,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out AsyncStatus
	)

	if hr != 0 {
		return AsyncStatusCanceled, winrt.NewError(hr)
	}

	return out, nil
}

func (v *IAsyncInfo) GetErrorCode() (HResult, error) {
	var out HResult
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetErrorCode,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out HResult
	)

	if hr != 0 {
		return HResult{}, winrt.NewError(hr)
	}

	return out, nil
}

func (v *IAsyncInfo) Cancel() error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().Cancel,
		uintptr(unsafe.Pointer(v)), // this
	)

	if hr != 0 {
		return winrt.NewError(hr)
	}

	return nil
}

func (v *IAsyncInfo) Close() error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().Close,
		uintptr(unsafe.Pointer(v)), // this
	)

	if hr != 0 {
		return winrt.NewError(hr)
	}

	return nil
}
