// Code generated by gowinrt. DO NOT EDIT.

//go:build windows

//nolint:all
package foundation

import (
	"unsafe"

	"github.com/go-ole/go-ole"
)

const GUIDIAsyncInfo string = "00000036-0000-0000-c000-000000000046"
const SignatureIAsyncInfo string = "{00000036-0000-0000-c000-000000000046}"

type IAsyncInfo struct {
	ole.IInspectable
}

type IAsyncInfoVtbl struct {
	ole.IInspectableVtbl

	GetId        uintptr
	GetStatus    uintptr
	GetErrorCode uintptr
	Cancel       uintptr
	Close        uintptr
}

func (v *IAsyncInfo) VTable() *IAsyncInfoVtbl {
	return (*IAsyncInfoVtbl)(unsafe.Pointer(v.RawVTable))
}
