// Code generated by gowinrt. DO NOT EDIT.

//go:build windows

//nolint:all
package foundation

import (
	"syscall"
	"unsafe"

	"github.com/zandercodes/gowinrt/winrt"
)

const GUIDIPropertyValue string = "4bd682dd-7554-40e9-9a9b-82654ede7e62"
const SignatureIPropertyValue string = "{4bd682dd-7554-40e9-9a9b-82654ede7e62}"

type IPropertyValue struct {
	winrt.IInspectable
}

type IPropertyValueVtbl struct {
	winrt.IInspectableVtbl

	GetType             uintptr
	GetIsNumericScalar  uintptr
	GetUInt8            uintptr
	GetInt16            uintptr
	GetUInt16           uintptr
	GetInt32            uintptr
	GetUInt32           uintptr
	GetInt64            uintptr
	GetUInt64           uintptr
	GetSingle           uintptr
	GetDouble           uintptr
	GetChar16           uintptr
	GetBoolean          uintptr
	GetString           uintptr
	GetGuid             uintptr
	GetDateTime         uintptr
	GetTimeSpan         uintptr
	GetPoint            uintptr
	GetSize             uintptr
	GetRect             uintptr
	GetUInt8Array       uintptr
	GetInt16Array       uintptr
	GetUInt16Array      uintptr
	GetInt32Array       uintptr
	GetUInt32Array      uintptr
	GetInt64Array       uintptr
	GetUInt64Array      uintptr
	GetSingleArray      uintptr
	GetDoubleArray      uintptr
	GetChar16Array      uintptr
	GetBooleanArray     uintptr
	GetStringArray      uintptr
	GetInspectableArray uintptr
	GetGuidArray        uintptr
	GetDateTimeArray    uintptr
	GetTimeSpanArray    uintptr
	GetPointArray       uintptr
	GetSizeArray        uintptr
	GetRectArray        uintptr
}

func (v *IPropertyValue) VTable() *IPropertyValueVtbl {
	return (*IPropertyValueVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *IPropertyValue) GetType() (PropertyType, error) {
	var out PropertyType
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetType,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out PropertyType
	)

	if hr != 0 {
		return PropertyTypeEmpty, winrt.NewError(hr)
	}

	return out, nil
}

func (v *IPropertyValue) GetIsNumericScalar() (bool, error) {
	var out bool
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetIsNumericScalar,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out bool
	)

	if hr != 0 {
		return false, winrt.NewError(hr)
	}

	return out, nil
}

func (v *IPropertyValue) GetUInt8() (uint8, error) {
	var out uint8
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetUInt8,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out uint8
	)

	if hr != 0 {
		return 0, winrt.NewError(hr)
	}

	return out, nil
}

func (v *IPropertyValue) GetInt16() (int16, error) {
	var out int16
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetInt16,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out int16
	)

	if hr != 0 {
		return 0, winrt.NewError(hr)
	}

	return out, nil
}

func (v *IPropertyValue) GetUInt16() (uint16, error) {
	var out uint16
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetUInt16,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out uint16
	)

	if hr != 0 {
		return 0, winrt.NewError(hr)
	}

	return out, nil
}

func (v *IPropertyValue) GetInt32() (int32, error) {
	var out int32
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetInt32,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out int32
	)

	if hr != 0 {
		return 0, winrt.NewError(hr)
	}

	return out, nil
}

func (v *IPropertyValue) GetUInt32() (uint32, error) {
	var out uint32
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetUInt32,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out uint32
	)

	if hr != 0 {
		return 0, winrt.NewError(hr)
	}

	return out, nil
}

func (v *IPropertyValue) GetInt64() (int64, error) {
	var out int64
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetInt64,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out int64
	)

	if hr != 0 {
		return 0, winrt.NewError(hr)
	}

	return out, nil
}

func (v *IPropertyValue) GetUInt64() (uint64, error) {
	var out uint64
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetUInt64,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out uint64
	)

	if hr != 0 {
		return 0, winrt.NewError(hr)
	}

	return out, nil
}

func (v *IPropertyValue) GetSingle() (float32, error) {
	var out float32
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetSingle,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out float32
	)

	if hr != 0 {
		return 0.0, winrt.NewError(hr)
	}

	return out, nil
}

func (v *IPropertyValue) GetDouble() (float64, error) {
	var out float64
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetDouble,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out float64
	)

	if hr != 0 {
		return 0.0, winrt.NewError(hr)
	}

	return out, nil
}

func (v *IPropertyValue) GetChar16() (byte, error) {
	var out byte
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetChar16,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out byte
	)

	if hr != 0 {
		return 0, winrt.NewError(hr)
	}

	return out, nil
}

func (v *IPropertyValue) GetBoolean() (bool, error) {
	var out bool
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetBoolean,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out bool
	)

	if hr != 0 {
		return false, winrt.NewError(hr)
	}

	return out, nil
}

func (v *IPropertyValue) GetString() (string, error) {
	var outHStr winrt.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetString,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", winrt.NewError(hr)
	}

	out := outHStr.String()
	winrt.DeleteHString(outHStr)
	return out, nil
}

func (v *IPropertyValue) GetGuid() (syscall.GUID, error) {
	var out syscall.GUID
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetGuid,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out syscall.GUID
	)

	if hr != 0 {
		return syscall.GUID{}, winrt.NewError(hr)
	}

	return out, nil
}

func (v *IPropertyValue) GetDateTime() (DateTime, error) {
	var out DateTime
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetDateTime,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out DateTime
	)

	if hr != 0 {
		return DateTime{}, winrt.NewError(hr)
	}

	return out, nil
}

func (v *IPropertyValue) GetTimeSpan() (TimeSpan, error) {
	var out TimeSpan
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetTimeSpan,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out TimeSpan
	)

	if hr != 0 {
		return TimeSpan{}, winrt.NewError(hr)
	}

	return out, nil
}

func (v *IPropertyValue) GetPoint() (Point, error) {
	var out Point
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetPoint,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out Point
	)

	if hr != 0 {
		return Point{}, winrt.NewError(hr)
	}

	return out, nil
}

func (v *IPropertyValue) GetSize() (Size, error) {
	var out Size
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetSize,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out Size
	)

	if hr != 0 {
		return Size{}, winrt.NewError(hr)
	}

	return out, nil
}

func (v *IPropertyValue) GetRect() (Rect, error) {
	var out Rect
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetRect,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out Rect
	)

	if hr != 0 {
		return Rect{}, winrt.NewError(hr)
	}

	return out, nil
}
