// Code generated by gowinrt. DO NOT EDIT.

//go:build windows

//nolint:all
package foundation

const SignatureTimeSpan string = "struct(Windows.Foundation.TimeSpan;i8)"

type TimeSpan struct {
	Duration int64
}
