// Code generated by gowinrt. DO NOT EDIT.

//go:build windows

//nolint:all
package control

import (
	"syscall"
	"unsafe"

	"github.com/zandercodes/gowinrt/windows/storage/streams"
	"github.com/zandercodes/gowinrt/winrt"
)

const SignatureGlobalSystemMediaTransportControlsSessionMediaProperties string = "rc(Windows.Media.Control.GlobalSystemMediaTransportControlsSessionMediaProperties;{68856cf6-adb4-54b2-ac16-05837907acb6})"

type GlobalSystemMediaTransportControlsSessionMediaProperties struct {
	winrt.IUnknown
}

func (impl *GlobalSystemMediaTransportControlsSessionMediaProperties) GetTitle() (string, error) {
	itf := impl.MustQueryInterface(winrt.NewGUID(GUIDiGlobalSystemMediaTransportControlsSessionMediaProperties))
	defer itf.Release()
	v := (*iGlobalSystemMediaTransportControlsSessionMediaProperties)(unsafe.Pointer(itf))
	return v.GetTitle()
}

func (impl *GlobalSystemMediaTransportControlsSessionMediaProperties) GetArtist() (string, error) {
	itf := impl.MustQueryInterface(winrt.NewGUID(GUIDiGlobalSystemMediaTransportControlsSessionMediaProperties))
	defer itf.Release()
	v := (*iGlobalSystemMediaTransportControlsSessionMediaProperties)(unsafe.Pointer(itf))
	return v.GetArtist()
}

func (impl *GlobalSystemMediaTransportControlsSessionMediaProperties) GetThumbnail() (*streams.IRandomAccessStreamReference, error) {
	itf := impl.MustQueryInterface(winrt.NewGUID(GUIDiGlobalSystemMediaTransportControlsSessionMediaProperties))
	defer itf.Release()
	v := (*iGlobalSystemMediaTransportControlsSessionMediaProperties)(unsafe.Pointer(itf))
	return v.GetThumbnail()
}

const GUIDiGlobalSystemMediaTransportControlsSessionMediaProperties string = "68856cf6-adb4-54b2-ac16-05837907acb6"
const SignatureiGlobalSystemMediaTransportControlsSessionMediaProperties string = "{68856cf6-adb4-54b2-ac16-05837907acb6}"

type iGlobalSystemMediaTransportControlsSessionMediaProperties struct {
	winrt.IInspectable
}

type iGlobalSystemMediaTransportControlsSessionMediaPropertiesVtbl struct {
	winrt.IInspectableVtbl

	GetTitle           uintptr
	GetSubtitle        uintptr
	GetAlbumArtist     uintptr
	GetArtist          uintptr
	GetAlbumTitle      uintptr
	GetTrackNumber     uintptr
	GetGenres          uintptr
	GetAlbumTrackCount uintptr
	GetPlaybackType    uintptr
	GetThumbnail       uintptr
}

func (v *iGlobalSystemMediaTransportControlsSessionMediaProperties) VTable() *iGlobalSystemMediaTransportControlsSessionMediaPropertiesVtbl {
	return (*iGlobalSystemMediaTransportControlsSessionMediaPropertiesVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iGlobalSystemMediaTransportControlsSessionMediaProperties) GetTitle() (string, error) {
	var outHStr winrt.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetTitle,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", winrt.NewError(hr)
	}

	out := outHStr.String()
	winrt.DeleteHString(outHStr)
	return out, nil
}

func (v *iGlobalSystemMediaTransportControlsSessionMediaProperties) GetArtist() (string, error) {
	var outHStr winrt.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetArtist,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", winrt.NewError(hr)
	}

	out := outHStr.String()
	winrt.DeleteHString(outHStr)
	return out, nil
}

func (v *iGlobalSystemMediaTransportControlsSessionMediaProperties) GetThumbnail() (*streams.IRandomAccessStreamReference, error) {
	var out *streams.IRandomAccessStreamReference
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetThumbnail,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out streams.IRandomAccessStreamReference
	)

	if hr != 0 {
		return nil, winrt.NewError(hr)
	}

	return out, nil
}
