// Code generated by gowinrt. DO NOT EDIT.

//go:build windows

//nolint:all
package control

import (
	"unsafe"

	"github.com/zandercodes/gowinrt/winrt"
)

const SignatureMediaPropertiesChangedEventArgs string = "rc(Windows.Media.Control.MediaPropertiesChangedEventArgs;{7d3741cb-adf0-5cef-91ba-cfabcdd77678})"

type MediaPropertiesChangedEventArgs struct {
	winrt.IUnknown
}

const GUIDiMediaPropertiesChangedEventArgs string = "7d3741cb-adf0-5cef-91ba-cfabcdd77678"
const SignatureiMediaPropertiesChangedEventArgs string = "{7d3741cb-adf0-5cef-91ba-cfabcdd77678}"

type iMediaPropertiesChangedEventArgs struct {
	winrt.IInspectable
}

type iMediaPropertiesChangedEventArgsVtbl struct {
	winrt.IInspectableVtbl
}

func (v *iMediaPropertiesChangedEventArgs) VTable() *iMediaPropertiesChangedEventArgsVtbl {
	return (*iMediaPropertiesChangedEventArgsVtbl)(unsafe.Pointer(v.RawVTable))
}
